### ISSUE TITLE
Unit Testing

### ISSUE THREAD

**Issue by slashformotion** [AustL/PygameWidgets#27]
perhaps it's time to include some tests.

I tried it on a separate branch here https://github.com/slashformotion/PygameWidgets/tree/travis-ci

**Comment by AustL** [comment]
In a sense, the project already has, admittedly not rigorous, unit tests for each widget. However, continuous integration would be something good to add. I suppose the issue is that the project is primarily visual, which means automated testing is a bit difficult to achieve. It would still be good to catch any runtime errors though.

**Comment by slashformotion** [comment]
I have absolutely no idea how to test that using CI tools like Travis. There is no gui so....

**Comment by slashformotion** [comment]
You can't really test the UI side of things with CI ?
